// let d = new Date()
// console.log(d)
// // get methods
// console.log(d.getDate())
// console.log(d.getMonth())
// console.log(d.getFullYear())
// console.log(d.getHours())
// console.log(d.getMinutes())
// console.log(d.getSeconds())
// console.log(d.getMilliseconds())
// console.log(d.getDay())
// console.log(d.getTime())
// console.log(Date.now())

let d = new Date("Februray 16, 2026 10:110:10")
console.log(d)
console.log(d.getMonth())